# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Autogenerated Dockerfile for MCP Search Server
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
RUN npm install --ignore-scripts --no-audit --no-fund

# Copy source and build
COPY src ./src
RUN npm run build

# Use production environment
ENV NODE_ENV=production

# Run the MCP server over stdio
ENTRYPOINT ["node", "build/index.js"]
